name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:

jobs:
  build:
    name: build / ${{ matrix.name }} PHP-${{ matrix.php }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]

        include:
          # Linux
          - { name: ubuntu, os: ubuntu-20.04 }
          # macOS
          - { name: macOS,  os: macos-12 }

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: phpize
        run: phpize

      - name: Configure
        run: ./configure

      - name: Compile
        run: |
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install

      - name: Extension Info
        run: |
          echo "extension=spx.so" >> $(php -r "echo php_ini_loaded_file();")
          php --ini
          php --ri spx

      - name: Run Tests
        run: make test

      - name: Upload build artifacts after Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: debug-PHP-${{ matrix.php }}
          path: |
            ${{ github.workspace }}/*.log
          retention-days: 7
