name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:

jobs:
  build:
    name: build / ${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.name }}-${{ matrix.compiler }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]

        name:
          - ubuntu
          - macOS

        include:
          # Linux
          - { name: linux, ts: 'nts', compiler: 'gcc',   os: ubuntu-20.04 }
          # macOS
          - { name: macOS, ts: 'nts', compiler: 'clang', os: macos-11 }

    steps:
      - uses: actions/checkout@v2

      # configure spx artifact name in next format:
      #   {php}-{ts}-{os.name}-{compiler}
      #   spx-php-8.1-nts-Linux-gcc
      - name: Set artifact name
        id: setup-artifact
        run: |
          echo "::set-output name=spx_file_name::spx-php-${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.name }}-${{ matrix.compiler }}"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        if: runner.os == 'macOS'
        run: brew install zlib

      - name: phpize
        run: phpize

      - name: Configure
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            ./configure --with-zlib-dir=$(brew --prefix)/opt/zlib
          else
            ./configure
          fi

      - name: Compile
        run: |
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install

      - name: Extension Info
        run: |
          php --ini
          php -d extension=./modules/spx.so --ri spx

      - name: Run Tests
        run: make test
        env:
          NO_INTERACTION: 1
          REPORT_EXIT_STATUS: 1
          TEST_PHP_ARGS: "--show-diff"

      - name: Upload build artifacts after Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: debug-${{ steps.setup-artifact.outputs.spx_file_name }}
          path: |
            ${{ github.workspace }}/*.log
            ${{ github.workspace }}/tests/*.log
          retention-days: 7

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup-artifact.outputs.spx_file_name }}.zip
          path: |
            ${{ github.workspace }}/modules/spx.so
            ${{ github.workspace }}/assets/**
            ${{ github.workspace }}/LICENSE
